/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as MotoristaRouteImport } from './routes/motorista'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as MotoristaRotasRouteImport } from './routes/motorista.rotas'
import { Route as MotoristaNotificacoesRouteImport } from './routes/motorista.notificacoes'
import { Route as MotoristaHistoricoRouteImport } from './routes/motorista.historico'
import { Route as MotoristaFinanceiroRouteImport } from './routes/motorista.financeiro'
import { Route as MotoristaDashboardRouteImport } from './routes/motorista.dashboard'
import { Route as MotoristaComproveiRouteImport } from './routes/motorista.comprovei'
import { Route as MotoristaCombustivelRouteImport } from './routes/motorista.combustivel'
import { Route as AdminSyncLogsRouteImport } from './routes/admin.sync-logs'
import { Route as AdminRotasRouteImport } from './routes/admin.rotas'
import { Route as AdminRelatoriosRouteImport } from './routes/admin.relatorios'
import { Route as AdminPagamentosRouteImport } from './routes/admin.pagamentos'
import { Route as AdminNotificacoesRouteImport } from './routes/admin.notificacoes'
import { Route as AdminMotoristasRouteImport } from './routes/admin.motoristas'
import { Route as AdminMetasRouteImport } from './routes/admin.metas'
import { Route as AdminFinanceiroRouteImport } from './routes/admin.financeiro'
import { Route as AdminEmpresasRouteImport } from './routes/admin.empresas'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin.configuracoes'
import { Route as AdminComproveiRouteImport } from './routes/admin.comprovei'
import { Route as AdminCombustivelRouteImport } from './routes/admin.combustivel'
import { Route as MotoristaRotasNovaRouteImport } from './routes/motorista.rotas.nova'
import { Route as AdminRotasNovaRouteImport } from './routes/admin.rotas.nova'
import { Route as AdminRotasRouteIdRouteImport } from './routes/admin.rotas.$routeId'
import { Route as AdminMotoristasDriverIdRouteImport } from './routes/admin.motoristas.$driverId'
import { Route as ApiPublicHooksComproveiSyncRouteImport } from './routes/api/public/hooks/comprovei-sync'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const MotoristaRoute = MotoristaRouteImport.update({
  id: '/motorista',
  path: '/motorista',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const MotoristaRotasRoute = MotoristaRotasRouteImport.update({
  id: '/rotas',
  path: '/rotas',
  getParentRoute: () => MotoristaRoute,
} as any)
const MotoristaNotificacoesRoute = MotoristaNotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => MotoristaRoute,
} as any)
const MotoristaHistoricoRoute = MotoristaHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => MotoristaRoute,
} as any)
const MotoristaFinanceiroRoute = MotoristaFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => MotoristaRoute,
} as any)
const MotoristaDashboardRoute = MotoristaDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => MotoristaRoute,
} as any)
const MotoristaComproveiRoute = MotoristaComproveiRouteImport.update({
  id: '/comprovei',
  path: '/comprovei',
  getParentRoute: () => MotoristaRoute,
} as any)
const MotoristaCombustivelRoute = MotoristaCombustivelRouteImport.update({
  id: '/combustivel',
  path: '/combustivel',
  getParentRoute: () => MotoristaRoute,
} as any)
const AdminSyncLogsRoute = AdminSyncLogsRouteImport.update({
  id: '/sync-logs',
  path: '/sync-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRotasRoute = AdminRotasRouteImport.update({
  id: '/rotas',
  path: '/rotas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRelatoriosRoute = AdminRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagamentosRoute = AdminPagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificacoesRoute = AdminNotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMotoristasRoute = AdminMotoristasRouteImport.update({
  id: '/motoristas',
  path: '/motoristas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMetasRoute = AdminMetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceiroRoute = AdminFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmpresasRoute = AdminEmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminComproveiRoute = AdminComproveiRouteImport.update({
  id: '/comprovei',
  path: '/comprovei',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCombustivelRoute = AdminCombustivelRouteImport.update({
  id: '/combustivel',
  path: '/combustivel',
  getParentRoute: () => AdminRoute,
} as any)
const MotoristaRotasNovaRoute = MotoristaRotasNovaRouteImport.update({
  id: '/nova',
  path: '/nova',
  getParentRoute: () => MotoristaRotasRoute,
} as any)
const AdminRotasNovaRoute = AdminRotasNovaRouteImport.update({
  id: '/nova',
  path: '/nova',
  getParentRoute: () => AdminRotasRoute,
} as any)
const AdminRotasRouteIdRoute = AdminRotasRouteIdRouteImport.update({
  id: '/$routeId',
  path: '/$routeId',
  getParentRoute: () => AdminRotasRoute,
} as any)
const AdminMotoristasDriverIdRoute = AdminMotoristasDriverIdRouteImport.update({
  id: '/$driverId',
  path: '/$driverId',
  getParentRoute: () => AdminMotoristasRoute,
} as any)
const ApiPublicHooksComproveiSyncRoute =
  ApiPublicHooksComproveiSyncRouteImport.update({
    id: '/api/public/hooks/comprovei-sync',
    path: '/api/public/hooks/comprovei-sync',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/motorista': typeof MotoristaRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/admin/combustivel': typeof AdminCombustivelRoute
  '/admin/comprovei': typeof AdminComproveiRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/empresas': typeof AdminEmpresasRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/metas': typeof AdminMetasRoute
  '/admin/motoristas': typeof AdminMotoristasRouteWithChildren
  '/admin/notificacoes': typeof AdminNotificacoesRoute
  '/admin/pagamentos': typeof AdminPagamentosRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/rotas': typeof AdminRotasRouteWithChildren
  '/admin/sync-logs': typeof AdminSyncLogsRoute
  '/motorista/combustivel': typeof MotoristaCombustivelRoute
  '/motorista/comprovei': typeof MotoristaComproveiRoute
  '/motorista/dashboard': typeof MotoristaDashboardRoute
  '/motorista/financeiro': typeof MotoristaFinanceiroRoute
  '/motorista/historico': typeof MotoristaHistoricoRoute
  '/motorista/notificacoes': typeof MotoristaNotificacoesRoute
  '/motorista/rotas': typeof MotoristaRotasRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/motoristas/$driverId': typeof AdminMotoristasDriverIdRoute
  '/admin/rotas/$routeId': typeof AdminRotasRouteIdRoute
  '/admin/rotas/nova': typeof AdminRotasNovaRoute
  '/motorista/rotas/nova': typeof MotoristaRotasNovaRoute
  '/api/public/hooks/comprovei-sync': typeof ApiPublicHooksComproveiSyncRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/motorista': typeof MotoristaRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/admin/combustivel': typeof AdminCombustivelRoute
  '/admin/comprovei': typeof AdminComproveiRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/empresas': typeof AdminEmpresasRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/metas': typeof AdminMetasRoute
  '/admin/motoristas': typeof AdminMotoristasRouteWithChildren
  '/admin/notificacoes': typeof AdminNotificacoesRoute
  '/admin/pagamentos': typeof AdminPagamentosRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/rotas': typeof AdminRotasRouteWithChildren
  '/admin/sync-logs': typeof AdminSyncLogsRoute
  '/motorista/combustivel': typeof MotoristaCombustivelRoute
  '/motorista/comprovei': typeof MotoristaComproveiRoute
  '/motorista/dashboard': typeof MotoristaDashboardRoute
  '/motorista/financeiro': typeof MotoristaFinanceiroRoute
  '/motorista/historico': typeof MotoristaHistoricoRoute
  '/motorista/notificacoes': typeof MotoristaNotificacoesRoute
  '/motorista/rotas': typeof MotoristaRotasRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/admin/motoristas/$driverId': typeof AdminMotoristasDriverIdRoute
  '/admin/rotas/$routeId': typeof AdminRotasRouteIdRoute
  '/admin/rotas/nova': typeof AdminRotasNovaRoute
  '/motorista/rotas/nova': typeof MotoristaRotasNovaRoute
  '/api/public/hooks/comprovei-sync': typeof ApiPublicHooksComproveiSyncRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/motorista': typeof MotoristaRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/admin/combustivel': typeof AdminCombustivelRoute
  '/admin/comprovei': typeof AdminComproveiRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/empresas': typeof AdminEmpresasRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/metas': typeof AdminMetasRoute
  '/admin/motoristas': typeof AdminMotoristasRouteWithChildren
  '/admin/notificacoes': typeof AdminNotificacoesRoute
  '/admin/pagamentos': typeof AdminPagamentosRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/rotas': typeof AdminRotasRouteWithChildren
  '/admin/sync-logs': typeof AdminSyncLogsRoute
  '/motorista/combustivel': typeof MotoristaCombustivelRoute
  '/motorista/comprovei': typeof MotoristaComproveiRoute
  '/motorista/dashboard': typeof MotoristaDashboardRoute
  '/motorista/financeiro': typeof MotoristaFinanceiroRoute
  '/motorista/historico': typeof MotoristaHistoricoRoute
  '/motorista/notificacoes': typeof MotoristaNotificacoesRoute
  '/motorista/rotas': typeof MotoristaRotasRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/motoristas/$driverId': typeof AdminMotoristasDriverIdRoute
  '/admin/rotas/$routeId': typeof AdminRotasRouteIdRoute
  '/admin/rotas/nova': typeof AdminRotasNovaRoute
  '/motorista/rotas/nova': typeof MotoristaRotasNovaRoute
  '/api/public/hooks/comprovei-sync': typeof ApiPublicHooksComproveiSyncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/motorista'
    | '/reset-password'
    | '/admin/combustivel'
    | '/admin/comprovei'
    | '/admin/configuracoes'
    | '/admin/dashboard'
    | '/admin/empresas'
    | '/admin/financeiro'
    | '/admin/metas'
    | '/admin/motoristas'
    | '/admin/notificacoes'
    | '/admin/pagamentos'
    | '/admin/relatorios'
    | '/admin/rotas'
    | '/admin/sync-logs'
    | '/motorista/combustivel'
    | '/motorista/comprovei'
    | '/motorista/dashboard'
    | '/motorista/financeiro'
    | '/motorista/historico'
    | '/motorista/notificacoes'
    | '/motorista/rotas'
    | '/admin/'
    | '/admin/motoristas/$driverId'
    | '/admin/rotas/$routeId'
    | '/admin/rotas/nova'
    | '/motorista/rotas/nova'
    | '/api/public/hooks/comprovei-sync'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/motorista'
    | '/reset-password'
    | '/admin/combustivel'
    | '/admin/comprovei'
    | '/admin/configuracoes'
    | '/admin/dashboard'
    | '/admin/empresas'
    | '/admin/financeiro'
    | '/admin/metas'
    | '/admin/motoristas'
    | '/admin/notificacoes'
    | '/admin/pagamentos'
    | '/admin/relatorios'
    | '/admin/rotas'
    | '/admin/sync-logs'
    | '/motorista/combustivel'
    | '/motorista/comprovei'
    | '/motorista/dashboard'
    | '/motorista/financeiro'
    | '/motorista/historico'
    | '/motorista/notificacoes'
    | '/motorista/rotas'
    | '/admin'
    | '/admin/motoristas/$driverId'
    | '/admin/rotas/$routeId'
    | '/admin/rotas/nova'
    | '/motorista/rotas/nova'
    | '/api/public/hooks/comprovei-sync'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/motorista'
    | '/reset-password'
    | '/admin/combustivel'
    | '/admin/comprovei'
    | '/admin/configuracoes'
    | '/admin/dashboard'
    | '/admin/empresas'
    | '/admin/financeiro'
    | '/admin/metas'
    | '/admin/motoristas'
    | '/admin/notificacoes'
    | '/admin/pagamentos'
    | '/admin/relatorios'
    | '/admin/rotas'
    | '/admin/sync-logs'
    | '/motorista/combustivel'
    | '/motorista/comprovei'
    | '/motorista/dashboard'
    | '/motorista/financeiro'
    | '/motorista/historico'
    | '/motorista/notificacoes'
    | '/motorista/rotas'
    | '/admin/'
    | '/admin/motoristas/$driverId'
    | '/admin/rotas/$routeId'
    | '/admin/rotas/nova'
    | '/motorista/rotas/nova'
    | '/api/public/hooks/comprovei-sync'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MotoristaRoute: typeof MotoristaRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicHooksComproveiSyncRoute: typeof ApiPublicHooksComproveiSyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motorista': {
      id: '/motorista'
      path: '/motorista'
      fullPath: '/motorista'
      preLoaderRoute: typeof MotoristaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/motorista/rotas': {
      id: '/motorista/rotas'
      path: '/rotas'
      fullPath: '/motorista/rotas'
      preLoaderRoute: typeof MotoristaRotasRouteImport
      parentRoute: typeof MotoristaRoute
    }
    '/motorista/notificacoes': {
      id: '/motorista/notificacoes'
      path: '/notificacoes'
      fullPath: '/motorista/notificacoes'
      preLoaderRoute: typeof MotoristaNotificacoesRouteImport
      parentRoute: typeof MotoristaRoute
    }
    '/motorista/historico': {
      id: '/motorista/historico'
      path: '/historico'
      fullPath: '/motorista/historico'
      preLoaderRoute: typeof MotoristaHistoricoRouteImport
      parentRoute: typeof MotoristaRoute
    }
    '/motorista/financeiro': {
      id: '/motorista/financeiro'
      path: '/financeiro'
      fullPath: '/motorista/financeiro'
      preLoaderRoute: typeof MotoristaFinanceiroRouteImport
      parentRoute: typeof MotoristaRoute
    }
    '/motorista/dashboard': {
      id: '/motorista/dashboard'
      path: '/dashboard'
      fullPath: '/motorista/dashboard'
      preLoaderRoute: typeof MotoristaDashboardRouteImport
      parentRoute: typeof MotoristaRoute
    }
    '/motorista/comprovei': {
      id: '/motorista/comprovei'
      path: '/comprovei'
      fullPath: '/motorista/comprovei'
      preLoaderRoute: typeof MotoristaComproveiRouteImport
      parentRoute: typeof MotoristaRoute
    }
    '/motorista/combustivel': {
      id: '/motorista/combustivel'
      path: '/combustivel'
      fullPath: '/motorista/combustivel'
      preLoaderRoute: typeof MotoristaCombustivelRouteImport
      parentRoute: typeof MotoristaRoute
    }
    '/admin/sync-logs': {
      id: '/admin/sync-logs'
      path: '/sync-logs'
      fullPath: '/admin/sync-logs'
      preLoaderRoute: typeof AdminSyncLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rotas': {
      id: '/admin/rotas'
      path: '/rotas'
      fullPath: '/admin/rotas'
      preLoaderRoute: typeof AdminRotasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/relatorios': {
      id: '/admin/relatorios'
      path: '/relatorios'
      fullPath: '/admin/relatorios'
      preLoaderRoute: typeof AdminRelatoriosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pagamentos': {
      id: '/admin/pagamentos'
      path: '/pagamentos'
      fullPath: '/admin/pagamentos'
      preLoaderRoute: typeof AdminPagamentosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notificacoes': {
      id: '/admin/notificacoes'
      path: '/notificacoes'
      fullPath: '/admin/notificacoes'
      preLoaderRoute: typeof AdminNotificacoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/motoristas': {
      id: '/admin/motoristas'
      path: '/motoristas'
      fullPath: '/admin/motoristas'
      preLoaderRoute: typeof AdminMotoristasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/metas': {
      id: '/admin/metas'
      path: '/metas'
      fullPath: '/admin/metas'
      preLoaderRoute: typeof AdminMetasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/financeiro': {
      id: '/admin/financeiro'
      path: '/financeiro'
      fullPath: '/admin/financeiro'
      preLoaderRoute: typeof AdminFinanceiroRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/empresas': {
      id: '/admin/empresas'
      path: '/empresas'
      fullPath: '/admin/empresas'
      preLoaderRoute: typeof AdminEmpresasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/comprovei': {
      id: '/admin/comprovei'
      path: '/comprovei'
      fullPath: '/admin/comprovei'
      preLoaderRoute: typeof AdminComproveiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/combustivel': {
      id: '/admin/combustivel'
      path: '/combustivel'
      fullPath: '/admin/combustivel'
      preLoaderRoute: typeof AdminCombustivelRouteImport
      parentRoute: typeof AdminRoute
    }
    '/motorista/rotas/nova': {
      id: '/motorista/rotas/nova'
      path: '/nova'
      fullPath: '/motorista/rotas/nova'
      preLoaderRoute: typeof MotoristaRotasNovaRouteImport
      parentRoute: typeof MotoristaRotasRoute
    }
    '/admin/rotas/nova': {
      id: '/admin/rotas/nova'
      path: '/nova'
      fullPath: '/admin/rotas/nova'
      preLoaderRoute: typeof AdminRotasNovaRouteImport
      parentRoute: typeof AdminRotasRoute
    }
    '/admin/rotas/$routeId': {
      id: '/admin/rotas/$routeId'
      path: '/$routeId'
      fullPath: '/admin/rotas/$routeId'
      preLoaderRoute: typeof AdminRotasRouteIdRouteImport
      parentRoute: typeof AdminRotasRoute
    }
    '/admin/motoristas/$driverId': {
      id: '/admin/motoristas/$driverId'
      path: '/$driverId'
      fullPath: '/admin/motoristas/$driverId'
      preLoaderRoute: typeof AdminMotoristasDriverIdRouteImport
      parentRoute: typeof AdminMotoristasRoute
    }
    '/api/public/hooks/comprovei-sync': {
      id: '/api/public/hooks/comprovei-sync'
      path: '/api/public/hooks/comprovei-sync'
      fullPath: '/api/public/hooks/comprovei-sync'
      preLoaderRoute: typeof ApiPublicHooksComproveiSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminMotoristasRouteChildren {
  AdminMotoristasDriverIdRoute: typeof AdminMotoristasDriverIdRoute
}

const AdminMotoristasRouteChildren: AdminMotoristasRouteChildren = {
  AdminMotoristasDriverIdRoute: AdminMotoristasDriverIdRoute,
}

const AdminMotoristasRouteWithChildren = AdminMotoristasRoute._addFileChildren(
  AdminMotoristasRouteChildren,
)

interface AdminRotasRouteChildren {
  AdminRotasRouteIdRoute: typeof AdminRotasRouteIdRoute
  AdminRotasNovaRoute: typeof AdminRotasNovaRoute
}

const AdminRotasRouteChildren: AdminRotasRouteChildren = {
  AdminRotasRouteIdRoute: AdminRotasRouteIdRoute,
  AdminRotasNovaRoute: AdminRotasNovaRoute,
}

const AdminRotasRouteWithChildren = AdminRotasRoute._addFileChildren(
  AdminRotasRouteChildren,
)

interface AdminRouteChildren {
  AdminCombustivelRoute: typeof AdminCombustivelRoute
  AdminComproveiRoute: typeof AdminComproveiRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminEmpresasRoute: typeof AdminEmpresasRoute
  AdminFinanceiroRoute: typeof AdminFinanceiroRoute
  AdminMetasRoute: typeof AdminMetasRoute
  AdminMotoristasRoute: typeof AdminMotoristasRouteWithChildren
  AdminNotificacoesRoute: typeof AdminNotificacoesRoute
  AdminPagamentosRoute: typeof AdminPagamentosRoute
  AdminRelatoriosRoute: typeof AdminRelatoriosRoute
  AdminRotasRoute: typeof AdminRotasRouteWithChildren
  AdminSyncLogsRoute: typeof AdminSyncLogsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCombustivelRoute: AdminCombustivelRoute,
  AdminComproveiRoute: AdminComproveiRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminEmpresasRoute: AdminEmpresasRoute,
  AdminFinanceiroRoute: AdminFinanceiroRoute,
  AdminMetasRoute: AdminMetasRoute,
  AdminMotoristasRoute: AdminMotoristasRouteWithChildren,
  AdminNotificacoesRoute: AdminNotificacoesRoute,
  AdminPagamentosRoute: AdminPagamentosRoute,
  AdminRelatoriosRoute: AdminRelatoriosRoute,
  AdminRotasRoute: AdminRotasRouteWithChildren,
  AdminSyncLogsRoute: AdminSyncLogsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface MotoristaRotasRouteChildren {
  MotoristaRotasNovaRoute: typeof MotoristaRotasNovaRoute
}

const MotoristaRotasRouteChildren: MotoristaRotasRouteChildren = {
  MotoristaRotasNovaRoute: MotoristaRotasNovaRoute,
}

const MotoristaRotasRouteWithChildren = MotoristaRotasRoute._addFileChildren(
  MotoristaRotasRouteChildren,
)

interface MotoristaRouteChildren {
  MotoristaCombustivelRoute: typeof MotoristaCombustivelRoute
  MotoristaComproveiRoute: typeof MotoristaComproveiRoute
  MotoristaDashboardRoute: typeof MotoristaDashboardRoute
  MotoristaFinanceiroRoute: typeof MotoristaFinanceiroRoute
  MotoristaHistoricoRoute: typeof MotoristaHistoricoRoute
  MotoristaNotificacoesRoute: typeof MotoristaNotificacoesRoute
  MotoristaRotasRoute: typeof MotoristaRotasRouteWithChildren
}

const MotoristaRouteChildren: MotoristaRouteChildren = {
  MotoristaCombustivelRoute: MotoristaCombustivelRoute,
  MotoristaComproveiRoute: MotoristaComproveiRoute,
  MotoristaDashboardRoute: MotoristaDashboardRoute,
  MotoristaFinanceiroRoute: MotoristaFinanceiroRoute,
  MotoristaHistoricoRoute: MotoristaHistoricoRoute,
  MotoristaNotificacoesRoute: MotoristaNotificacoesRoute,
  MotoristaRotasRoute: MotoristaRotasRouteWithChildren,
}

const MotoristaRouteWithChildren = MotoristaRoute._addFileChildren(
  MotoristaRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MotoristaRoute: MotoristaRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicHooksComproveiSyncRoute: ApiPublicHooksComproveiSyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
